#!/bin/bash

BACK_DIR=/share/Backup
BACK_SRV="192.168.1.14"
BACK_USER="root"
back_dest=`hostname`
FILE_LIST="${HOME}/bin/${back_dest}.backup"
EXCLUDE_FILE="${HOME}/bin/${back_dest}.exclude"

if [ "$FILE_LIST" == "" ]; then
	echo "usage: backup {include file}"
	exit 1
fi

if ! test -f $FILE_LIST; then
	echo "ERROR: $FILE_LIST not found!"
	exit 1
fi

if ! test -f $EXCLUDE_FILE; then
	echo "ERROR: $EXCLUDE_FILE not found!"
	exit 1
fi

if ! which rsync>/dev/null 2>&1; then
	echo "rsync utility not found!!!"
	exit
fi


echo "backing up files to ${BACK_USER}@${BACK_SRV}:${BACK_DIR}/${back_dest}..."

while read file; do
	echo "backiing up ${file}..."
	rsync --links --exclude-from ${EXCLUDE_FILE} -avzhP "${file}" ${BACK_USER}@${BACK_SRV}:${BACK_DIR}/${back_dest}/ --delete-excluded
done < $FILE_LIST

exit

rsync --links --exclude-from ${EXCLUDE_FILE} -avzhP /home ${BACK_USER}@${BACK_SRV}:${BACK_DIR}/${back_dest}/ --delete-excluded
rsync --links --exclude-from ${EXCLUDE_FILE} -avzhP /usr/local ${BACK_USER}@${BACK_SRV}:${BACK_DIR}/${back_dest}/ --delete-excluded

