#!/bin/bash

sudo apt -y install autoconf curl build-essential libtool qtbase5-dev libevent-dev libminiupnpc-dev libnatpmp-dev libqrencode-dev libunivalue-dev libzmq3-dev libsqlite3-dev qt5-default libpcap-dev libncurses5-dev libprocps-dev libxtst-dev libxcb-util0-dev qttools5-dev-tools libdtkwidget-dev libdtkwm-dev pkg-config libboost-all-dev gettext

sudo ldconfig

mkdir ~/src
cd ~/src
wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
tar -xzvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix/
../dist/configure --prefix=/usr/local --enable-cxx
sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' ../dbinc/atomic.h
make
sudo make install

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
sudo ldconfig

cd ~/git-repos; git clone https://github.com/bitcoin/bitcoin.git
cd ~/git-repos/bitcoin
./autogen.sh
#./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX --with-incompatible-bdb
./configure

make --jobs=5

