#!/bin/bash

rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm

yum -y install epel-release http://yum.theforeman.org/releases/1.8/el6/x86_64/foreman-release.rpm

yum -y install foreman-installer

foreman-installer

/etc/init.d/iptables stop

chkconfig --del iptables
