#!/bin/bash

source mfuncs

OS=`get_os`

echo "installing docker on $OS"

if [ "$OS" == "rhel8" ]; then
	sudo dnf -y config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
	sudo dnf -y install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
	sudo dnf -y install --nobest docker-ce
	sudo systemctl enable --now docker
	sudo groupadd docker
	sudo usermod -aG docker $USER
fi
