#!/bin/bash

source mfuncs

OS=`get_os`

echo "installing rbenv on $OS"

if [ "$OS" == "rhel8" ]; then
    sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
    sudo yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel \
    libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison \
    curl sqlite-devel
elif [ "$OS" == "ubuntu" ] || [ "$OS" == "debian" ]; then
    sudo apt -y install git curl autoconf bison build-essential \
    libssl-dev libyaml-dev libreadline6-dev zlib1g-dev \
    libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
fi

git clone https://github.com/rbenv/rbenv.git ~/.rbenv

cd ~/.rbenv && src/configure && make -C src

echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

echo "Logout and log back in to apply the changes"
