#!/bin/bash

source mfuncs

OS=`get_os`

echo "installing vs code on $OS"

if [ "$OS" == "centos" ] || [ "$OS" == "rhel" ]; then
	sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
	sleep 1
	sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
	sudo yum -y update
	sudo yum -y install code
elif [ "$OS" == "rhel8" ]; then
        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        sleep 1
        sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
        sudo dnf -y install code
elif [ "$OS" == "ubuntu" ] || [ "$OS" == "debian" ]; then
	cd /tmp
	sudo apt update
	sudo apt-get -y install apt-transport-https
	wget https://packages.microsoft.com/keys/microsoft.asc
	cat microsoft.asc | gpg --dearmor > microsoft.gpg
	sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
	sudo apt-get update
	sudo apt-get -y install apt-transport-https code
fi
